permalink: pretty
markdown: kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

collections:
  articoli_2017:
    output: true
    permalink: /it/:collection/:title
